import re, pathlib
p = pathlib.Path('crypto_bot.py')
text = p.read_text(encoding='utf-8')
start = text.index('MICRO_TOP10_OPTIMIZED_STRATEGIES = {')
end = text.index('MICRO_EXCLUDED_BASES', start)
new = '''MICRO_TOP10_OPTIMIZED_STRATEGIES = {
    # === Deployed 2026-06-20 16:00 optimizer winners (4H cycle, 14d lookback, vol_ratio>=1.0, min_trades>=10) ===
    # Entry: delay=3, max_rank=3, chg=3-10%, green_confirm, upper_wick<=1.2%, min_vol=1.0x, reclaim=false
    # Closed trades: 13, net_avg=1.177%, PF=5.20, WR=69.2%, max_loss=-1.16%
    # Top result (atr2-15): 72.7% WR, 1.287% net_avg, PF=6.71, max_loss=-1.16%, trades=11
    "auto_top1_4h_d3_r3_chg3-10_green_uw1.2_vol10_sl1.0_be0.6_tr0.9x0.4_t8": {
        "version": "auto_top1_4h",
        "entry_delay_bars": 3,
        "max_rank": 3,
        "min_change_1h_pct": 3.0,
        "max_change_1h_pct": 10.0,
        "min_current_change_1h_pct": 0.0,
        "require_change_reclaim": False,
        "require_green_confirm": True,
        "max_upper_wick_pct": 1.2,
        "min_volume_ratio": 1.0,
        "reclaim_entry_price": False,
        "shadow_only": False,
        "stop_loss_pct": 1.0,
        "breakeven_after_pct": 0.6,
        "trailing_start_pct": 0.9,
        "trailing_giveback_pct": 0.4,
        "time_stop_bars": 8,
    },
    "auto_top2_4h_d3_r3_chg3-10_green_uw1.2_vol10_sl1.0_be0.6_tr0.9x0.4_t12": {
        "version": "auto_top2_4h",
        "entry_delay_bars": 3,
        "max_rank": 3,
        "min_change_1h_pct": 3.0,
        "max_change_1h_pct": 10.0,
        "min_current_change_1h_pct": 0.0,
        "require_change_reclaim": False,
        "require_green_confirm": True,
        "max_upper_wick_pct": 1.2,
        "min_volume_ratio": 1.0,
        "reclaim_entry_price": False,
        "shadow_only": False,
        "stop_loss_pct": 1.0,
        "breakeven_after_pct": 0.6,
        "trailing_start_pct": 0.9,
        "trailing_giveback_pct": 0.4,
        "time_stop_bars": 12,
    },
    "auto_top3_4h_d3_r3_chg3-10_green_uw1.2_vol10_sl1.0_be0.6_tr0.9x0.4_t18": {
        "version": "auto_top3_4h",
        "entry_delay_bars": 3,
        "max_rank": 3,
        "min_change_1h_pct": 3.0,
        "max_change_1h_pct": 10.0,
        "min_current_change_1h_pct": 0.0,
        "require_change_reclaim": False,
        "require_green_confirm": True,
        "max_upper_wick_pct": 1.2,
        "min_volume_ratio": 1.0,
        "reclaim_entry_price": False,
        "shadow_only": False,
        "stop_loss_pct": 1.0,
        "breakeven_after_pct": 0.6,
        "trailing_start_pct": 0.9,
        "trailing_giveback_pct": 0.4,
        "time_stop_bars": 18,
    },

    # === Strategy 4.1 (production backtest positive) ===
    # Kept from previous: net_avg=0.087%, WR=44.4%, PF=1.21, max_loss=-0.96%
    "strategy4_1_breakout_confirmation": {
        "version": "strategy4.1",
        "entry_delay_bars": 0,
        "max_rank": 5,
        "min_change_1h_pct": 0.4,
        "max_change_1h_pct": 4.0,
        "min_current_change_1h_pct": 0.2,
        "require_change_reclaim": True,
        "require_green_confirm": True,
        "max_upper_wick_pct": 0.45,
        "min_volume_ratio": 1.4,
        "reclaim_entry_price": True,
        "shadow_only": False,
        "stop_loss_pct": 0.8,
        "breakeven_after_pct": 0.2,
        "trailing_start_pct": 1.6,
        "trailing_giveback_pct": 0.6,
        "time_stop_bars": 8,
    },
    # === Strategy 20 (6h/12h VWAP reclaim, net_avg=0.465%, PF=2.11) ===
    "strategy20_6h12h_cool_vwap_reclaim": {
        "version": "strategy20",
        "entry_delay_bars": 0,
        "max_rank": 20,
        "min_change_1h_pct": 0.0,
        "max_change_1h_pct": 3.0,
        "min_current_change_1h_pct": 0.0,
        "require_change_reclaim": True,
        "require_green_confirm": False,
        "max_upper_wick_pct": 0.65,
        "min_volume_ratio": 0.5,
        "reclaim_entry_price": True,
        "shadow_only": False,
        "stop_loss_pct": 0.7,
        "breakeven_after_pct": 0.25,
        "trailing_start_pct": 2.8,
        "trailing_giveback_pct": 0.9,
        "time_stop_bars": 24,
    },
    # === Top5 quality score strategy (shadow-only) ===
    "top5dplus_score95_chg2_5_sl1_tr06x03_t6": {
        "version": "top5dplus",
        "entry_delay_bars": 0,
        "max_rank": 5,
        "min_change_1h_pct": 2.0,
        "max_change_1h_pct": 5.0,
        "min_current_change_1h_pct": 0.0,
        "require_change_reclaim": False,
        "min_volume_ratio": 0.0,
        "shadow_only": True,
        "quality_score_threshold": 95.0,
        "quality_rank_weight": 8.0,
        "quality_change_peak_pct": 5.0,
        "quality_change_peak_score": 25.0,
        "quality_change_penalty": 7.0,
        "quality_volume_weight": 8.0,
        "quality_volume_cap_score": 20.0,
        "quality_ema_bonus": 12.0,
        "quality_green_bonus": 8.0,
        "quality_upper_wick_bonus": 8.0,
        "quality_close_pos_bonus": 6.0,
        "quality_body_bonus": 5.0,
        "quality_atr_bonus": 5.0,
        "quality_max_upper_wick_ratio": 0.25,
        "quality_min_close_position": 0.60,
        "quality_min_body_ratio": 0.25,
        "quality_atr_bonus_max_pct": 1.8,
        "stop_loss_pct": 1.0,
        "breakeven_after_pct": 0.6,
        "trailing_start_pct": 0.6,
        "trailing_giveback_pct": 0.3,
        "time_stop_bars": 6,
    },
    # === Legacy strategies (kept for backward compat, not in default active set) ===
    "top10scan_d2_r5_chg2-8_cur2_vol1.2_sl0.8_tr1.5x0.5_t12": {
        "version": "top10scan",
        "entry_delay_bars": 2,
        "max_rank": 5,
        "min_change_1h_pct": 2.0,
        "max_change_1h_pct": 8.0,
        "min_current_change_1h_pct": 2.0,
        "require_change_reclaim": False,
        "require_green_confirm": True,
        "max_upper_wick_pct": 999.9,
        "min_volume_ratio": 1.2,
        "reclaim_entry_price": False,
        "shadow_only": True,
        "stop_loss_pct": 0.8,
        "breakeven_after_pct": 0.6,
        "trailing_start_pct": 1.5,
        "trailing_giveback_pct": 0.5,
        "time_stop_bars": 12,
    },
    "top10scan6_d1_r3_chg3_12_cur1_sl08_tr15x05_t12": {
        "version": "top10scan6",
        "entry_delay_bars": 1,
        "max_rank": 3,
        "min_change_1h_pct": 3.0,
        "max_change_1h_pct": 12.0,
        "min_current_change_1h_pct": 1.0,
        "require_change_reclaim": True,
        "require_green_confirm": True,
        "max_upper_wick_pct": 999.9,
        "min_volume_ratio": 0.0,
        "reclaim_entry_price": False,
        "shadow_only": True,
        "stop_loss_pct": 0.8,
        "breakeven_after_pct": 0.6,
        "trailing_start_pct": 1.5,
        "trailing_giveback_pct": 0.5,
        "time_stop_bars": 12,
    },
    "top10scan1_d1_r3_chg3_12_cur1_sl1_tr15x05_t12": {
        "version": "top10scan1",
        "entry_delay_bars": 1,
        "max_rank": 3,
        "min_change_1h_pct": 3.0,
        "max_change_1h_pct": 12.0,
        "min_current_change_1h_pct": 1.0,
        "require_change_reclaim": True,
        "require_green_confirm": True,
        "max_upper_wick_pct": 999.9,
        "min_volume_ratio": 0.0,
        "reclaim_entry_price": False,
        "shadow_only": True,
        "stop_loss_pct": 1.0,
        "breakeven_after_pct": 0.6,
        "trailing_start_pct": 1.5,
        "trailing_giveback_pct": 0.5,
        "time_stop_bars": 12,
    },
    "top10scan1v_d1_r3_chg3_12_cur1_vol12_sl1_tr15x05_t12": {
        "version": "top10scan1v",
        "entry_delay_bars": 1,
        "max_rank": 3,
        "min_change_1h_pct": 3.0,
        "max_change_1h_pct": 12.0,
        "min_current_change_1h_pct": 1.0,
        "require_change_reclaim": True,
        "require_green_confirm": True,
        "max_upper_wick_pct": 999.9,
        "min_volume_ratio": 1.2,
        "reclaim_entry_price": False,
        "shadow_only": True,
        "stop_loss_pct": 1.0,
        "breakeven_after_pct": 0.6,
        "trailing_start_pct": 1.5,
        "trailing_giveback_pct": 0.5,
        "time_stop_bars": 12,
    },
    "top10shadow1_d0_r5_chg2_15_cur0_sl1_tr1x05_t12": {
        "version": "top10shadow1",
        "entry_delay_bars": 0,
        "max_rank": 5,
        "min_change_1h_pct": 2.0,
        "max_change_1h_pct": 15.0,
        "min_current_change_1h_pct": 0.0,
        "require_change_reclaim": False,
        "require_green_confirm": False,
        "max_upper_wick_pct": 999.9,
        "min_volume_ratio": 0.0,
        "reclaim_entry_price": False,
        "shadow_only": True,
        "stop_loss_pct": 1.0,
        "breakeven_after_pct": 0.6,
        "trailing_start_pct": 1.0,
        "trailing_giveback_pct": 0.5,
        "time_stop_bars": 12,
    },
    "top10v1_rank5_chg3_10_sl1_trail09_t12": {
        "version": "top10v1",
        "entry_delay_bars": 0,
        "max_rank": 5,
        "min_change_1h_pct": 3.0,
        "max_change_1h_pct": 10.0,
        "min_current_change_1h_pct": 0.0,
        "require_change_reclaim": False,
        "require_green_confirm": False,
        "max_upper_wick_pct": 999.9,
        "min_volume_ratio": 0.0,
        "reclaim_entry_price": False,
        "shadow_only": False,
        "stop_loss_pct": 1.0,
        "breakeven_after_pct": 0.6,
        "trailing_start_pct": 0.9,
        "trailing_giveback_pct": 0.4,
        "time_stop_bars": 12,
    },
    "top10v3_rank5_chg3_10_sl08_trail09_t12": {
        "version": "top10v3",
        "entry_delay_bars": 0,
        "max_rank": 5,
        "min_change_1h_pct": 3.0,
        "max_change_1h_pct": 10.0,
        "min_current_change_1h_pct": 0.0,
        "require_change_reclaim": False,
        "require_green_confirm": False,
        "max_upper_wick_pct": 999.9,
        "min_volume_ratio": 0.0,
        "reclaim_entry_price": False,
        "shadow_only": False,
        "stop_loss_pct": 0.8,
        "breakeven_after_pct": 0.6,
        "trailing_start_pct": 0.9,
        "trailing_giveback_pct": 0.4,
        "time_stop_bars": 12,
    },
    "top10v5_delay1_rank3_chg1_5_sl15_trail12_t12": {
        "version": "top10v5",
        "entry_delay_bars": 1,
        "max_rank": 3,
        "min_change_1h_pct": 1.0,
        "max_change_1h_pct": 5.0,
        "min_current_change_1h_pct": 0.0,
        "require_change_reclaim": False,
        "require_green_confirm": False,
        "max_upper_wick_pct": 999.9,
        "min_volume_ratio": 0.0,
        "reclaim_entry_price": False,
        "shadow_only": False,
        "stop_loss_pct": 1.5,
        "breakeven_after_pct": 0.8,
        "trailing_start_pct": 1.2,
        "trailing_giveback_pct": 0.6,
        "time_stop_bars": 12,
    },
}
'''
text = text[:start] + new + text[end:]
p.write_text(text, encoding='utf-8')
print('rewrote MICRO_TOP10_OPTIMIZED_STRATEGIES')
